<?php

function industry_page_data(string $slug): ?array
{
    $pages = [
        "retail-bpo" => [
            "name" => "Retail",
            "image" => "indus1.webp",
            "hero" => "Built for Retail. Ready for Every Customer Moment.",
            "audience" => "retailers, omnichannel brands, marketplaces, and consumer product companies",
            "challenge" => "Retail teams must manage seasonal demand, rising service expectations, order complexity, and margin pressure across every customer channel.",
            "outcome" => "protect customer loyalty, improve order accuracy, and scale support without adding fixed overhead",
            "services" => [
                "Omnichannel Customer Support" => "Phone, chat, email, and social support|Product and availability inquiries|Complaint resolution and escalation",
                "Order Management" => "Order entry and validation|Order status updates|Cancellations and amendments",
                "Returns & Refunds" => "Return authorization support|Refund coordination|Exchange and replacement processing",
                "Loyalty Program Support" => "Member enrollment|Points and rewards inquiries|Retention and win-back outreach",
                "Catalog & Inventory Operations" => "Product data maintenance|Inventory updates|SKU and listing quality checks",
                "Retail Back-Office Services" => "Data entry and reconciliation|Vendor coordination|Reporting and quality assurance",
            ],
            "segments" => "Omnichannel Retailers|Customer care, order management, returns;Consumer Brands|Product support, loyalty, warranty coordination;Marketplaces|Seller support, catalog operations, dispute handling;Specialty Retail|Appointment support, product inquiries, retention;Subscription Commerce|Account support, renewals, payment recovery",
        ],
        "automotive-bpo" => [
            "name" => "Automotive",
            "image" => "indus2.webp",
            "hero" => "Automotive BPO Built for Every Mile of the Customer Journey.",
            "audience" => "vehicle manufacturers, dealer groups, mobility companies, parts suppliers, and service networks",
            "challenge" => "Automotive organizations balance complex dealer operations, service scheduling, warranty workflows, connected customers, and high expectations for response time.",
            "outcome" => "strengthen owner loyalty, accelerate service workflows, and give dealerships dependable operational capacity",
            "services" => [
                "Customer Care & Roadside Support" => "Inbound owner assistance|Roadside case coordination|Escalation and follow-up",
                "Service Scheduling" => "Appointment booking|Recall outreach|Maintenance reminder programs",
                "Dealer Support" => "Dealer help desk|CRM updates|Lead routing and follow-up",
                "Warranty & Claims Administration" => "Claim intake|Document validation|Status communication",
                "Sales & Lead Management" => "Lead qualification|Test-drive scheduling|Customer re-engagement",
                "Automotive Back Office" => "Vehicle data entry|Parts order support|Reporting and quality control",
            ],
            "segments" => "OEMs|Owner care, recalls, warranty support;Dealer Groups|Scheduling, lead management, CRM support;Mobility Providers|Rider and driver support, case management;Parts Suppliers|Order support, dealer inquiries, data processing;EV Companies|Charging support, onboarding, connected services",
        ],
        "travel-hospitality-bpo" => [
            "name" => "Travel & Hospitality",
            "image" => "indus3.webp",
            "hero" => "Guest Experience Support from Booking to Return.",
            "audience" => "airlines, hotels, travel platforms, tour operators, vacation rentals, and mobility brands",
            "challenge" => "Travel demand changes quickly, disruptions happen without warning, and guests expect immediate, empathetic help in every time zone.",
            "outcome" => "deliver responsive guest care, recover disrupted journeys, and maintain service quality around the clock",
            "services" => [
                "Reservations & Booking Support" => "New reservations|Booking changes|Availability and fare inquiries",
                "Disruption Management" => "Cancellation support|Rebooking assistance|Guest notification workflows",
                "Guest Services" => "Pre-arrival assistance|In-stay support|Post-stay follow-up",
                "Loyalty Program Operations" => "Member servicing|Points inquiries|Tier and benefit support",
                "Travel Back Office" => "Itinerary processing|Document verification|Supplier reconciliation",
                "Digital Travel Support" => "Chat and messaging support|Review response support|Social care and escalation",
            ],
            "segments" => "Airlines|Reservations, disruption support, loyalty;Hotels & Resorts|Guest care, booking, post-stay support;Online Travel Agencies|Booking support, refunds, supplier coordination;Vacation Rentals|Guest and host support, case resolution;Tour Operators|Itinerary support, documentation, traveler care",
        ],
        "telecommunications-bpo" => [
            "name" => "Telecommunications",
            "image" => "indus4.webp",
            "hero" => "Telecom Support Engineered for Always-On Customers.",
            "audience" => "telecom carriers, internet service providers, cable operators, network vendors, and connected service brands",
            "challenge" => "Telecom customers expect fast activation, reliable billing, immediate technical help, and clear communication during outages or service changes.",
            "outcome" => "reduce resolution time, improve first-contact performance, and protect subscriber retention",
            "services" => [
                "Tier 1-3 Technical Support" => "Connectivity troubleshooting|Device and router support|Ticket escalation",
                "Subscriber Customer Care" => "Plan and account inquiries|Service changes|Complaint resolution",
                "Billing & Payment Support" => "Invoice inquiries|Payment assistance|Adjustment processing",
                "Provisioning & Activation" => "New service activation|Number porting support|Order validation",
                "Retention & Win-Back" => "Churn prevention|Offer support|Reactivation outreach",
                "Network Operations Support" => "Outage communications|Ticket monitoring|Field service coordination",
            ],
            "segments" => "Mobile Carriers|Subscriber care, billing, retention;Internet Providers|Technical support, activation, outage care;Cable Operators|Account care, service changes, troubleshooting;Network Vendors|Technical help desk, case administration;IoT Providers|Device support, onboarding, monitoring",
        ],
        "insurance-bpo" => [
            "name" => "Insurance",
            "image" => "indus5.webp",
            "hero" => "Insurance BPO Built for Accuracy, Trust, and Speed.",
            "audience" => "property and casualty carriers, life insurers, health plans, brokers, MGAs, and insurtech companies",
            "challenge" => "Insurance operations depend on accurate records, responsive policyholder communication, disciplined claims workflows, and strict regulatory controls.",
            "outcome" => "shorten processing cycles, improve policyholder service, and scale administration with stronger quality control",
            "services" => [
                "Policyholder Customer Service" => "Coverage inquiries|Policy changes|Billing and payment assistance",
                "Claims Administration Support" => "First notice of loss|Document collection|Claim status updates",
                "Policy Administration" => "New business processing|Endorsements and renewals|Policy data maintenance",
                "Underwriting Support" => "Application intake|Data verification|Risk file preparation",
                "Agent & Broker Support" => "Appointment support|Commission inquiries|Case escalation",
                "Insurance Back Office" => "Document indexing|Quality assurance|Reporting and reconciliation",
            ],
            "segments" => "Property & Casualty|Policy service, claims intake, renewals;Life & Annuity|Application processing, policy administration;Health Insurance|Member services, enrollment, claims support;Brokers & MGAs|Agent support, quoting administration;Insurtech|Digital customer care, operations, data processing",
        ],
        "energy-bpo" => [
            "name" => "Energy",
            "image" => "indus7.webp",
            "hero" => "Energy BPO for Reliable Service and Smarter Operations.",
            "audience" => "electricity providers, renewable energy companies, oil and gas operators, energy retailers, and service contractors",
            "challenge" => "Energy organizations manage complex customer accounts, field activity, billing data, regulatory documentation, and service continuity across changing demand.",
            "outcome" => "improve customer communication, maintain accurate operational data, and support reliable service delivery",
            "services" => [
                "Energy Customer Care" => "Account inquiries|Service requests|Complaint and escalation handling",
                "Billing Operations" => "Invoice support|Payment processing|Billing adjustment workflows",
                "Meter Data Services" => "Meter data entry|Validation and exception handling|Usage reporting",
                "Field Service Coordination" => "Work order scheduling|Technician dispatch support|Completion follow-up",
                "Outage & Incident Support" => "Inbound outage reporting|Status communications|Case documentation",
                "Compliance Back Office" => "Regulatory documentation|Data quality review|Operational reporting",
            ],
            "segments" => "Energy Retailers|Customer care, billing, retention;Renewable Energy|Enrollment, service support, data operations;Oil & Gas|Back-office administration, reporting;Field Service Networks|Scheduling, dispatch, work orders;Energy Technology|Technical support, customer onboarding",
        ],
        "utility-bpo" => [
            "name" => "Utility",
            "image" => "indus8.webp",
            "hero" => "Utility BPO That Keeps Customers and Operations Connected.",
            "audience" => "electric, gas, water, waste, and municipal utility providers",
            "challenge" => "Utility providers must deliver essential services while handling high-volume billing inquiries, service orders, outage events, and strict reporting requirements.",
            "outcome" => "raise service responsiveness, improve account accuracy, and coordinate essential workflows at scale",
            "services" => [
                "Utility Customer Service" => "Account inquiries|Move-in and move-out requests|Complaint resolution",
                "Billing & Collections Support" => "Bill explanation|Payment arrangements|Collections outreach",
                "Service Order Management" => "Connection requests|Disconnection workflows|Order status tracking",
                "Outage Communications" => "Outage intake|Customer notifications|Restoration updates",
                "Meter & Usage Processing" => "Reading validation|Exception processing|Usage data entry",
                "Utility Back Office" => "Document processing|Regulatory reporting|Data quality assurance",
            ],
            "segments" => "Electric Utilities|Billing, outage care, service orders;Gas Utilities|Account support, field coordination;Water Providers|Customer service, meter processing;Municipal Utilities|Resident support, payments, records;Waste Services|Scheduling, account care, route support",
        ],
        "technology-bpo" => [
            "name" => "Technology & SaaS",
            "image" => "indus9.webp",
            "hero" => "Technology BPO Built to Support Adoption and Scale.",
            "audience" => "SaaS companies, software vendors, hardware brands, cloud platforms, fintechs, and emerging technology businesses",
            "challenge" => "Technology companies need to onboard users quickly, resolve technical issues, maintain product data, and scale customer operations without slowing innovation.",
            "outcome" => "accelerate customer adoption, protect retention, and expand operational capacity alongside product growth",
            "services" => [
                "Technical Support" => "Tier 1-3 troubleshooting|Ticket management|Bug and escalation documentation",
                "SaaS Customer Success" => "User onboarding|Adoption outreach|Renewal support",
                "Product Support" => "Feature inquiries|Account configuration|Knowledge base guidance",
                "Trust & Safety Operations" => "Content review|User case handling|Policy escalation",
                "Data & AI Operations" => "Data annotation|Quality review|Dataset preparation",
                "Technology Back Office" => "CRM administration|Order processing|Reporting and QA",
            ],
            "segments" => "SaaS Platforms|Onboarding, technical support, retention;Consumer Technology|Product care, warranty, troubleshooting;Cloud Services|User support, account administration;AI Companies|Annotation, moderation, data quality;Fintech Platforms|Customer operations, verification support",
        ],
        "government-bpo" => [
            "name" => "Government & Public Sector",
            "image" => "indus10.webp",
            "hero" => "Public Sector Support Built for Access, Accuracy, and Accountability.",
            "audience" => "government agencies, municipalities, public authorities, education bodies, and government contractors",
            "challenge" => "Public sector organizations must improve citizen access, process growing case volumes, maintain accurate records, and deliver transparent service within defined policies.",
            "outcome" => "expand citizen support capacity, reduce administrative backlogs, and strengthen process visibility",
            "services" => [
                "Citizen Contact Center" => "Program inquiries|Application guidance|Case status support",
                "Case Processing" => "Application intake|Eligibility document review|Case data updates",
                "Records Management" => "Document indexing|Records requests|Archival support",
                "Public Program Support" => "Enrollment assistance|Appointment scheduling|Outbound notifications",
                "Data Validation" => "Data entry|Duplicate review|Quality assurance",
                "Reporting & Compliance" => "Operational reporting|Audit file preparation|SLA monitoring",
            ],
            "segments" => "Municipalities|Resident service, permits, scheduling;Public Benefits Programs|Enrollment, case support, documentation;Transportation Authorities|Rider support, case management;Education Agencies|Applicant support, records processing;Government Contractors|Program operations, reporting, QA",
        ],
        "legal-process-outsourcing" => [
            "name" => "Legal",
            "image" => "indus11.webp",
            "hero" => "Legal Process Outsourcing Built for Precision and Confidentiality.",
            "audience" => "law firms, corporate legal departments, legal service providers, insurers, and compliance teams",
            "challenge" => "Legal teams face expanding document volumes, deadline pressure, costly routine work, and strict requirements for accuracy and confidentiality.",
            "outcome" => "reduce administrative workload, organize legal information, and give attorneys more time for substantive work",
            "services" => [
                "Document Review Support" => "Document classification|Relevance review support|Quality control",
                "Contract Administration" => "Contract abstraction|Metadata entry|Obligation tracking",
                "Legal Research Support" => "Case and statute research|Citation checking|Research summaries",
                "E-Discovery Operations" => "Data organization|Document coding|Review workflow support",
                "Case File Management" => "Matter setup|File organization|Deadline and docket updates",
                "Legal Back Office" => "Billing support|Client intake|Records and reporting",
            ],
            "segments" => "Law Firms|Document review, research, case administration;Corporate Legal Teams|Contracts, compliance records, intake;Insurance Legal Operations|Claims files, document processing;Legal Technology|Platform support, data operations;Compliance Teams|Monitoring, records, reporting",
        ],
        "financial-services-bpo" => [
            "name" => "Financial Services",
            "image" => "indus12.webp",
            "hero" => "Financial Services BPO Built for Control and Customer Confidence.",
            "audience" => "banks, lenders, fintechs, payment companies, wealth managers, and financial service providers",
            "challenge" => "Financial organizations must deliver fast service while maintaining accurate transactions, disciplined controls, secure data handling, and auditable processes.",
            "outcome" => "improve processing accuracy, strengthen customer support, and scale controlled financial operations",
            "services" => [
                "Financial Customer Service" => "Account inquiries|Transaction support|Complaint handling",
                "Loan Operations Support" => "Application intake|Document verification|Servicing administration",
                "Payments Back Office" => "Payment exception handling|Reconciliation support|Chargeback administration",
                "KYC Operations Support" => "Customer document collection|Data validation|Case preparation",
                "Accounts Payable & Receivable" => "Invoice processing|Cash application|Aging follow-up",
                "Reporting & Reconciliation" => "Account reconciliation|Data quality review|Management reporting",
            ],
            "segments" => "Banks & Credit Unions|Customer care, account administration;Lenders|Application processing, servicing support;Fintechs|Digital support, verification operations;Payment Providers|Disputes, reconciliation, merchant support;Wealth Managers|Client administration, records, reporting",
        ],
        "ecommerce-bpo" => [
            "name" => "eCommerce",
            "image" => "indus13.webp",
            "hero" => "eCommerce BPO That Turns Every Order into Loyalty.",
            "audience" => "online retailers, direct-to-consumer brands, marketplaces, subscription businesses, and social commerce companies",
            "challenge" => "eCommerce brands must handle fast-moving orders, delivery questions, returns, marketplace operations, and customer conversations across multiple channels.",
            "outcome" => "improve conversion support, reduce order friction, and retain customers after every purchase",
            "services" => [
                "eCommerce Customer Support" => "Pre-sale product inquiries|Order assistance|Post-purchase support",
                "Order Processing" => "Order validation|Status updates|Cancellation and modification support",
                "Returns & Refund Management" => "Return authorization|Refund coordination|Exchange support",
                "Marketplace Operations" => "Seller support|Listing maintenance|Dispute administration",
                "Catalog Management" => "Product data entry|Content enrichment|SKU quality review",
                "Subscription Support" => "Account changes|Renewal assistance|Payment recovery outreach",
            ],
            "segments" => "DTC Brands|Customer care, order support, retention;Online Retailers|Orders, returns, catalog operations;Marketplaces|Buyer and seller support, disputes;Subscription Brands|Account care, renewals, payment recovery;Social Commerce|Messaging support, order administration",
        ],
        "real-estate-bpo" => [
            "name" => "Real Estate",
            "image" => "indus14.webp",
            "hero" => "Real Estate BPO Built to Move Leads, Listings, and Residents Forward.",
            "audience" => "brokerages, property managers, developers, real estate platforms, mortgage service firms, and facility operators",
            "challenge" => "Real estate organizations manage time-sensitive leads, property data, resident requests, transaction documents, and vendor coordination across distributed portfolios.",
            "outcome" => "respond to prospects faster, organize property operations, and improve resident and client service",
            "services" => [
                "Lead Qualification" => "Inbound lead response|Prospect qualification|Viewing appointment scheduling",
                "Property Management Support" => "Resident inquiries|Maintenance request intake|Renewal coordination",
                "Listing Administration" => "Listing data entry|Photo and content updates|MLS quality checks",
                "Transaction Coordination" => "Document collection|Milestone tracking|Stakeholder follow-up",
                "Tenant & Resident Support" => "Move-in assistance|Account inquiries|Issue escalation",
                "Real Estate Back Office" => "Vendor coordination|Data maintenance|Portfolio reporting",
            ],
            "segments" => "Brokerages|Lead response, listing support, transactions;Property Managers|Resident care, maintenance coordination;Developers|Buyer support, appointment scheduling;Real Estate Platforms|User support, listing operations;Facility Operators|Service desk, vendor coordination",
        ],
        "gaming-bpo" => [
            "name" => "Gaming",
            "image" => "indus15.webp",
            "hero" => "Gaming Support Built for Players, Communities, and Live Operations.",
            "audience" => "game studios, publishers, platforms, esports organizations, and interactive entertainment companies",
            "challenge" => "Gaming communities expect fast, knowledgeable support while studios manage account issues, moderation, live events, payments, and player safety at global scale.",
            "outcome" => "protect player experience, strengthen communities, and support live operations around the clock",
            "services" => [
                "Player Support" => "Account and access help|Gameplay inquiries|Ticket resolution",
                "Technical Game Support" => "Installation troubleshooting|Connectivity support|Bug documentation",
                "Community Moderation" => "Chat moderation|Forum support|Escalation handling",
                "Trust & Safety" => "Player report review|Policy enforcement support|Fraud case escalation",
                "Payments & Account Support" => "Purchase inquiries|Refund administration|Subscription support",
                "Live Operations Support" => "Event support|Player communications|Knowledge base updates",
            ],
            "segments" => "Game Studios|Player support, technical cases, QA;Publishers|Global support, community operations;Gaming Platforms|Account care, payments, trust and safety;Esports Organizations|Participant support, event operations;Mobile Games|High-volume support, moderation, retention",
        ],
        "home-services-bpo" => [
            "name" => "Home Services",
            "image" => "indus16.webp",
            "hero" => "Home Services BPO Built to Book More Jobs and Serve Every Customer.",
            "audience" => "HVAC, plumbing, electrical, cleaning, landscaping, pest control, and multi-service home service companies",
            "challenge" => "Home service businesses lose revenue when calls go unanswered, schedules are inefficient, technicians lack complete job details, or customers do not receive timely updates.",
            "outcome" => "capture more demand, improve technician utilization, and deliver dependable customer communication",
            "services" => [
                "Inbound Call Answering" => "Service inquiry handling|Emergency call triage|Lead capture",
                "Appointment Scheduling" => "Booking and rescheduling|Service window coordination|Reminder outreach",
                "Dispatch Support" => "Technician assignment support|Route and status updates|Customer notifications",
                "Estimate Follow-Up" => "Quote follow-up|Lead nurturing|Unbooked job recovery",
                "Customer Care" => "Job status inquiries|Complaint resolution|Post-service follow-up",
                "Home Services Back Office" => "Work order entry|Invoice administration|CRM data maintenance",
            ],
            "segments" => "HVAC Companies|Call answering, scheduling, dispatch;Plumbing & Electrical|Emergency triage, booking, follow-up;Cleaning Services|Recurring scheduling, account care;Pest Control|Appointment support, renewal outreach;Multi-Service Franchises|Centralized customer care and operations",
        ],
        "home-warranty-bpo" => [
            "name" => "Home Warranty",
            "image" => "indus17.webp",
            "hero" => "Home Warranty BPO Built for Faster Claims and Better Homeowner Care.",
            "audience" => "home warranty companies, service contract administrators, property protection plans, and repair networks",
            "challenge" => "Home warranty providers coordinate urgent homeowner needs, coverage verification, contractor networks, approvals, claims, and service follow-up across high case volumes.",
            "outcome" => "accelerate claim handling, improve homeowner communication, and coordinate service networks efficiently",
            "services" => [
                "Homeowner Customer Care" => "Coverage inquiries|Claim status support|Complaint resolution",
                "Claim Intake & Triage" => "New claim registration|Issue classification|Emergency escalation",
                "Coverage Verification" => "Plan and entitlement checks|Exclusion review support|Document validation",
                "Contractor Coordination" => "Service provider assignment|Appointment coordination|Status follow-up",
                "Authorization Support" => "Estimate collection|Approval workflow administration|Decision communication",
                "Warranty Back Office" => "Claim documentation|Invoice review support|Reporting and quality assurance",
            ],
            "segments" => "Home Warranty Providers|Claims, customer care, contractor coordination;Service Contract Administrators|Entitlement, approvals, records;Property Managers|Resident claims and repair coordination;Appliance Plans|Product claims, service scheduling;Repair Networks|Dispatch, status updates, documentation",
        ],
        "transportation-logistics-bpo" => [
            "name" => "Transportation & Logistics",
            "image" => "indus18.webp",
            "hero" => "Logistics BPO Built for Visibility, Velocity, and Reliable Delivery.",
            "audience" => "carriers, freight forwarders, 3PLs, delivery networks, brokers, warehouses, and transportation technology companies",
            "challenge" => "Transportation operations depend on real-time communication, accurate documents, shipment visibility, exception management, and coordination across customers, drivers, and partners.",
            "outcome" => "improve shipment visibility, resolve exceptions faster, and keep freight and information moving",
            "services" => [
                "Shipment Tracking Support" => "Status inquiries|Proactive shipment updates|Proof-of-delivery support",
                "Order & Load Processing" => "Order entry|Load tender administration|Data validation",
                "Dispatch Coordination" => "Driver communication|Pickup and delivery scheduling|Route status updates",
                "Freight Documentation" => "Bill of lading processing|Document indexing|Customs file preparation support",
                "Exception Management" => "Delay and damage case intake|Escalation coordination|Customer communication",
                "Logistics Back Office" => "Invoice audit support|Carrier data maintenance|Operational reporting",
            ],
            "segments" => "3PLs|Shipment support, order entry, customer care;Freight Forwarders|Documentation, tracking, exception handling;Last-Mile Delivery|Driver support, dispatch, customer updates;Carriers & Brokers|Load administration, status communication;Warehouses|Appointment scheduling, data processing",
        ],
    ];

    if (!isset($pages[$slug])) {
        return null;
    }

    $page = $pages[$slug];
    $page["slug"] = $slug;
    $page["primary_keyword"] = strtolower($page["name"]) . " BPO services";
    $page["meta_title"] = $page["name"] . " BPO Services & Solutions";
    $page["meta_description"] = "EmpireOneCX provides specialized " . strtolower($page["name"]) . " BPO services for customer support, back-office workflows, data processing, and scalable operations.";
    $page["keywords"] = implode(", ", [
        strtolower($page["name"]) . " bpo",
        strtolower($page["name"]) . " bpo services",
        strtolower($page["name"]) . " outsourcing",
        strtolower($page["name"]) . " customer support outsourcing",
        strtolower($page["name"]) . " back office services",
        "business process outsourcing",
    ]);

    return $page;
}
