<?php

function location_page_data_es(string $slug): ?array
{
    $locations = [
        "canada" => [
            "name" => "Canadá",
            "english_slug" => "canada",
            "image" => "/assets/images/canada-skyscraper.webp",
            "title" => "Soporte de outsourcing CX y BPO en Canadá",
            "subtitle" => "Equipos de experiencia del cliente y back office compatibles con modelos nearshore para marcas canadienses.",
            "intro" => "EmpireOneCX ayuda a empresas canadienses a escalar atención al cliente, operaciones administrativas y flujos asistidos por IA con una entrega global segura y flexible.",
            "metaDescription" => "EmpireOneCX ofrece soporte de outsourcing CX y BPO en Canadá para servicio al cliente, back office, flujos asistidos por IA y soporte empresarial escalable.",
            "overview" => "Las empresas canadienses necesitan equipos de experiencia del cliente capaces de crecer sin sacrificar calidad de servicio, conciencia de cumplimiento ni consistencia de marca. EmpireOneCX apoya operaciones enfocadas en Canadá con agentes CX capacitados, especialistas de back office, procesos de QA y operaciones asistidas por IA.",
            "services" => [
                ["title" => "Equipos de experiencia del cliente", "text" => "Equipos dedicados para teléfono, correo electrónico, chat y soporte omnicanal, capacitados en sus productos, políticas y tono de marca."],
                ["title" => "Soporte back office", "text" => "Apoyo operativo para ingreso de datos, gestión de tickets, actualizaciones de CRM, manejo documental y flujos administrativos recurrentes."],
                ["title" => "Operaciones asistidas por IA", "text" => "Flujos prácticos de IA para enrutamiento, QA, soporte de conocimiento, reportes y automatización de procesos repetitivos."],
            ],
            "why" => "Nuestro modelo de entrega da a las empresas canadienses acceso a capacidad escalable, QA estructurado y flujos seguros, manteniendo la experiencia del cliente alineada con expectativas locales y estándares de marca.",
            "industries" => ["Retail y eCommerce", "Soporte de salud", "Servicios financieros", "SaaS y tecnología", "Servicios para el hogar", "Servicios profesionales"],
        ],
        "estados-unidos" => [
            "name" => "Estados Unidos",
            "english_slug" => "united-states",
            "image" => "/assets/images/USA.webp",
            "title" => "Soporte de outsourcing CX y BPO en Estados Unidos",
            "subtitle" => "Equipos escalables de atención al cliente y procesos empresariales para compañías de Estados Unidos.",
            "intro" => "EmpireOneCX ayuda a empresas estadounidenses a mejorar la capacidad de respuesta, reducir presión operativa y escalar funciones de atención y back office con equipos globales dedicados.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO para empresas de Estados Unidos, incluyendo servicio al cliente, ventas, back office, QA y operaciones asistidas por IA.",
            "overview" => "Las compañías de Estados Unidos suelen necesitar equipos ágiles que gestionen volúmenes crecientes de tickets, expectativas altas y complejidad operativa. EmpireOneCX ofrece soporte estructurado de CX y BPO para servicio al cliente, operaciones de ventas, flujos administrativos, QA y mejora de procesos habilitada por IA.",
            "services" => [
                ["title" => "Outsourcing de atención al cliente", "text" => "Soporte entrante, saliente, por correo, chat y mesa de ayuda diseñado para proteger la experiencia de marca y mejorar tiempos de respuesta."],
                ["title" => "Soporte de ventas y servicio", "text" => "Apoyo para seguimiento de leads, programación de citas, consultas de clientes, retención y coordinación de servicio."],
                ["title" => "Operaciones back office", "text" => "Apoyo administrativo y de procesos para gestión de datos, actualizaciones CRM, procesamiento documental y tareas recurrentes."],
            ],
            "why" => "EmpireOneCX da a empresas de Estados Unidos un socio operativo escalable con equipos dedicados, QA asistido por IA, flujos seguros y modelos flexibles diseñados para crecer.",
            "industries" => ["Retail y eCommerce", "Salud", "Seguros", "SaaS y tecnología", "Finanzas", "Bienes raíces"],
        ],
        "reino-unido" => [
            "name" => "Reino Unido",
            "english_slug" => "united-kingdom",
            "image" => "/assets/images/UK.webp",
            "title" => "Soporte de outsourcing CX y BPO en Reino Unido",
            "subtitle" => "Atención al cliente y back office para marcas del Reino Unido que atienden clientes locales y globales.",
            "intro" => "EmpireOneCX apoya a empresas del Reino Unido con servicio al cliente omnicanal, flujos conscientes de GDPR, back office y entrega asistida por IA.",
            "metaDescription" => "EmpireOneCX ofrece outsourcing CX y BPO para empresas del Reino Unido con soporte omnicanal, back office, QA, automatización y flujos conscientes de GDPR.",
            "overview" => "Las marcas del Reino Unido necesitan soporte al cliente receptivo, manejo cuidadoso de datos y capacidad operativa flexible. EmpireOneCX ayuda a equipos enfocados en Reino Unido a crear funciones dedicadas de CX y BPO para atención, tickets, back office, QA y automatización de procesos.",
            "services" => [
                ["title" => "Soporte CX omnicanal", "text" => "Atención por teléfono, correo electrónico, chat en vivo y canales digitales para recorridos de clientes del Reino Unido."],
                ["title" => "Flujos conscientes de GDPR", "text" => "Procesos diseñados alrededor de manejo cuidadoso de datos, acceso basado en roles y flujos seguros de información del cliente."],
                ["title" => "Control de calidad", "text" => "Monitoreo estructurado, scorecards, reportes y coaching para mejorar consistencia en las interacciones con clientes."],
            ],
            "why" => "EmpireOneCX combina capacidad global con disciplina de procesos para ayudar a empresas del Reino Unido a mejorar confiabilidad de servicio con flujos documentados, medibles y escalables.",
            "industries" => ["eCommerce", "Fintech", "Soporte de salud", "Viajes y hotelería", "SaaS", "Servicios profesionales"],
        ],
        "australia" => [
            "name" => "Australia",
            "english_slug" => "australia",
            "image" => "/assets/images/Australia.webp",
            "title" => "Soporte de outsourcing CX y BPO en Australia",
            "subtitle" => "Equipos confiables de atención al cliente y back office para empresas australianas.",
            "intro" => "EmpireOneCX ayuda a compañías australianas a ampliar cobertura de servicio, mejorar resiliencia operativa y atender clientes en canales digitales y de voz.",
            "metaDescription" => "EmpireOneCX ofrece soluciones BPO y soporte al cliente para empresas australianas que necesitan cobertura confiable, resiliencia operativa y equipos escalables.",
            "overview" => "Las empresas australianas suelen necesitar cobertura confiable, tiempos de respuesta rápidos y operaciones flexibles que puedan escalar sin agregar complejidad interna. EmpireOneCX apoya marcas enfocadas en Australia con atención al cliente, cobertura fuera de horario, back office, reportes y flujos asistidos por IA.",
            "services" => [
                ["title" => "Soporte fuera de horario", "text" => "Opciones de cobertura extendida para consultas de clientes, coordinación de servicio y soporte de overflow."],
                ["title" => "Equipos de atención al cliente", "text" => "Agentes dedicados capacitados para gestionar conversaciones en distintos canales con consistencia y empatía."],
                ["title" => "Operaciones back office", "text" => "Soporte para ingreso de datos, procesamiento de pedidos, tickets, actualizaciones CRM y flujos administrativos."],
            ],
            "why" => "EmpireOneCX ayuda a equipos australianos a fortalecer la experiencia del cliente con capacidad escalable, flujos documentados, visibilidad de QA y mejoras operativas asistidas por IA.",
            "industries" => ["Retail y eCommerce", "Viajes", "Servicios públicos", "Tecnología", "Servicios para el hogar", "Logística"],
        ],
        "emiratos-arabes-unidos" => [
            "name" => "Emiratos Árabes Unidos",
            "english_slug" => "uae",
            "image" => "/assets/images/UAE.webp",
            "title" => "Soporte de outsourcing CX y BPO en Emiratos Árabes Unidos",
            "subtitle" => "Soporte seguro y escalable de experiencia del cliente y operaciones para empresas de EAU y equipos regionales.",
            "intro" => "EmpireOneCX ayuda a empresas de EAU y marcas regionales a escalar interacción con clientes, flujos administrativos, soporte financiero y servicio multicanal.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO para empresas de Emiratos Árabes Unidos y equipos regionales con servicio multicanal, back office y operaciones seguras.",
            "overview" => "Las empresas de EAU suelen atender bases de clientes rápidas, multilingües y regionalmente diversas. EmpireOneCX apoya equipos enfocados en EAU con servicio al cliente, back office, flujos financieros y administrativos, servicio multicanal y prácticas de entrega segura.",
            "services" => [
                ["title" => "Soporte regional al cliente", "text" => "Equipos de servicio al cliente para voz, correo, chat y canales digitales que atienden necesidades de EAU y la región."],
                ["title" => "Flujos financieros y administrativos", "text" => "Soporte para operaciones financieras, documentación, manejo de datos, actualizaciones CRM y procesos administrativos."],
                ["title" => "Servicio multicanal", "text" => "Soporte coordinado en puntos de contacto del cliente con reportes, QA y visibilidad de procesos."],
            ],
            "why" => "EmpireOneCX aporta entrega global estructurada, procesos seguros y dotación escalable para empresas de EAU que necesitan soporte confiable sin frenar el crecimiento.",
            "industries" => ["Retail", "Finanzas", "Bienes raíces", "Viajes y hotelería", "Tecnología", "Servicios profesionales"],
        ],
        "marruecos" => [
            "name" => "Marruecos",
            "english_slug" => "morocco",
            "image" => "/assets/images/morocco-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Marruecos",
            "subtitle" => "Equipos multilingües de experiencia del cliente y back office para marcas enfocadas en EMEA.",
            "intro" => "EmpireOneCX ayuda a empresas a escalar soporte multilingüe, flujos administrativos y operaciones asistidas por IA con entrega alineada a Europa, Medio Oriente y África del Norte.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Marruecos para marcas que necesitan atención multilingüe, back office, cobertura EMEA y operaciones escalables.",
            "overview" => "Marruecos ofrece una posición sólida para marcas que necesitan capacidad multilingüe, familiaridad regional y operaciones eficientes. EmpireOneCX apoya equipos enfocados en Marruecos y EMEA con agentes CX, especialistas back office, QA y soporte asistido por IA.",
            "services" => [
                ["title" => "Soporte CX multilingüe", "text" => "Atención por teléfono, correo, chat y canales omnicanal para segmentos en francés, árabe, inglés y mercados regionales."],
                ["title" => "Flujos back office", "text" => "Soporte administrativo para CRM, manejo documental, tickets, ingreso de datos y operaciones recurrentes."],
                ["title" => "Cobertura regional", "text" => "Estructuras flexibles para horarios EMEA, overflow, monitoreo de calidad y soporte de procesos."],
            ],
            "why" => "Nuestro modelo ayuda a marcas enfocadas en Marruecos y EMEA a combinar soporte multilingüe, QA estructurado, flujos seguros y dotación escalable sin perder consistencia de marca.",
            "industries" => ["Viajes y hotelería", "Retail y eCommerce", "Telecomunicaciones", "SaaS y tecnología", "Servicios financieros", "Servicios profesionales"],
        ],
        "nicaragua" => [
            "name" => "Nicaragua",
            "english_slug" => "nicaragua",
            "image" => "/assets/images/nicaragua-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Nicaragua",
            "subtitle" => "Equipos nearshore de atención al cliente y operaciones para marcas de Norteamérica.",
            "intro" => "EmpireOneCX ayuda a empresas que atienden clientes norteamericanos a crear capacidad nearshore de CX, back office y soporte asistido por IA mediante entrega global estructurada.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Nicaragua para empresas que necesitan equipos nearshore, atención al cliente, back office y cobertura escalable.",
            "overview" => "Nicaragua es una opción práctica para compañías que necesitan cobertura receptiva, operaciones eficientes en costo y equipos alineados con expectativas de servicio norteamericanas. EmpireOneCX apoya entrega enfocada en Nicaragua con agentes, especialistas administrativos, QA y gestión de flujos.",
            "services" => [
                ["title" => "Soporte nearshore al cliente", "text" => "Soporte de voz, correo, chat y mesa de ayuda diseñado para expectativas y flujos de clientes norteamericanos."],
                ["title" => "Operaciones administrativas", "text" => "Soporte para mantenimiento CRM, actualizaciones de tickets, ingreso de datos, procesamiento de pedidos y tareas back office."],
                ["title" => "Cobertura escalable", "text" => "Dotación flexible para colas de overflow, horarios extendidos, demanda estacional y programas controlados por QA."],
            ],
            "why" => "EmpireOneCX ayuda a usar Nicaragua como parte de un modelo seguro y estructurado, con onboarding claro, QA y visibilidad de desempeño.",
            "industries" => ["Retail y eCommerce", "Servicios para el hogar", "Soporte de seguros", "Viajes y hotelería", "SaaS y tecnología", "Servicios profesionales"],
        ],
        "colombia" => [
            "name" => "Colombia",
            "english_slug" => "colombia",
            "image" => "/assets/images/colombia-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Colombia",
            "subtitle" => "Equipos bilingües de CX y BPO para operaciones de Latinoamérica y Norteamérica.",
            "intro" => "EmpireOneCX ayuda a marcas a escalar experiencia del cliente bilingüe, soporte de ventas, back office y flujos asistidos por IA con capacidad alineada a Colombia.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Colombia para atención bilingüe, ventas, back office, operaciones regionales y flujos asistidos por IA.",
            "overview" => "Colombia es un hub regional sólido para compañías que necesitan servicio bilingüe, calidad en atención al cliente y capacidad flexible. EmpireOneCX apoya programas enfocados en Colombia con agentes capacitados, especialistas back office, rutinas de QA y flujos asistidos por IA.",
            "services" => [
                ["title" => "Atención bilingüe al cliente", "text" => "Soporte en inglés y español para teléfono, correo, chat, help desk y programas omnicanal."],
                ["title" => "Soporte de ventas y servicio", "text" => "Seguimiento de leads, programación de citas, consultas de clientes, retención y coordinación de servicio."],
                ["title" => "Operaciones back office", "text" => "Soporte administrativo para actualizaciones CRM, gestión de datos, procesamiento documental y administración de colas."],
            ],
            "why" => "Nuestro modelo de Colombia brinda capacidad bilingüe, monitoreo de calidad, procesos seguros y dotación flexible para crecer.",
            "industries" => ["Retail y eCommerce", "Servicios financieros", "SaaS y tecnología", "Viajes y hotelería", "Soporte de salud", "Bienes raíces"],
        ],
        "venezuela" => [
            "name" => "Venezuela",
            "english_slug" => "venezuela",
            "image" => "/assets/images/venezuela-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Venezuela",
            "subtitle" => "Equipos de atención al cliente en español y procesos empresariales para cobertura escalable.",
            "intro" => "EmpireOneCX ayuda a empresas a ampliar atención al cliente en español, soporte administrativo y operaciones asistidas por IA con capacidad alineada a Venezuela.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Venezuela para atención al cliente en español, back office, dotación flexible y operaciones escalables.",
            "overview" => "Venezuela puede ayudar a empresas a ampliar capacidad de soporte en español y cobertura regional con equipos flexibles de atención y back office. EmpireOneCX apoya flujos enfocados en Venezuela con agentes capacitados, documentación de procesos, QA y estándares seguros.",
            "services" => [
                ["title" => "Soporte en español", "text" => "Atención por teléfono, correo, chat y canales digitales para segmentos de clientes hispanohablantes."],
                ["title" => "Apoyo back office", "text" => "Soporte para actualizaciones de tickets, ingreso de datos, manejo documental, mantenimiento CRM y colas administrativas."],
                ["title" => "Dotación flexible", "text" => "Cobertura para demanda de overflow, flujos recurrentes, colas de servicio y operaciones controladas por calidad."],
            ],
            "why" => "EmpireOneCX ayuda a programas enfocados en Venezuela a combinar soporte en español con capacitación clara, QA y gestión segura de flujos.",
            "industries" => ["Retail y eCommerce", "Telecomunicaciones", "Viajes y hotelería", "Servicios financieros", "Servicios para el hogar", "Servicios profesionales"],
        ],
        "bolivia" => [
            "name" => "Bolivia",
            "english_slug" => "bolivia",
            "image" => "/assets/images/bolivia-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Bolivia",
            "subtitle" => "Equipos de atención al cliente y back office para capacidad confiable en Latinoamérica.",
            "intro" => "EmpireOneCX ayuda a empresas a escalar servicio al cliente, operaciones administrativas y flujos asistidos por IA con equipos alineados a Bolivia.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Bolivia para atención al cliente, back office, soporte administrativo, QA y operaciones escalables.",
            "overview" => "Bolivia es una opción útil para marcas que buscan capacidad confiable en Latinoamérica, soporte administrativo y operaciones de atención en español. EmpireOneCX apoya programas enfocados en Bolivia con agentes CX, especialistas back office, QA y visibilidad de flujos.",
            "services" => [
                ["title" => "Equipos de servicio al cliente", "text" => "Soporte por teléfono, correo, chat y help desk para consultas, solicitudes de servicio y colas recurrentes."],
                ["title" => "Soporte administrativo", "text" => "Ingreso de datos, actualizaciones CRM, procesamiento documental, enrutamiento de tickets y flujos back office."],
                ["title" => "Flujos de calidad", "text" => "Monitoreo QA, reportes, soporte de conocimiento y coaching para mantener una entrega consistente."],
            ],
            "why" => "Nuestro modelo de Bolivia brinda capacidad escalable, opciones de soporte en español, QA estructurado y flujos seguros para crecimiento operativo.",
            "industries" => ["Retail y eCommerce", "Servicios financieros", "Viajes y hotelería", "Telecomunicaciones", "Servicios profesionales", "Servicios para el hogar"],
        ],
        "paraguay" => [
            "name" => "Paraguay",
            "english_slug" => "paraguay",
            "image" => "/assets/images/paraguay-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Paraguay",
            "subtitle" => "Equipos flexibles de CX y back office para operaciones eficientes en Latinoamérica.",
            "intro" => "EmpireOneCX ayuda a organizaciones a crear atención al cliente, back office y operaciones asistidas por IA alineadas a Paraguay con entrega global estructurada.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Paraguay para atención al cliente, back office, escalamiento operativo y flujos de servicio eficientes.",
            "overview" => "Paraguay puede apoyar empresas que necesitan capacidad eficiente en Latinoamérica, ejecución back office confiable y escalamiento flexible. EmpireOneCX ayuda a programas enfocados en Paraguay a lanzar atención al cliente y flujos operativos con procesos documentados, QA y visibilidad de desempeño.",
            "services" => [
                ["title" => "Soporte al cliente", "text" => "Soporte entrante, saliente, por correo, chat y help desk para consultas y flujos de servicio."],
                ["title" => "Equipos back office", "text" => "Soporte administrativo para gestión de tickets, ingreso de datos, actualizaciones CRM, documentos y tareas recurrentes."],
                ["title" => "Escalamiento operativo", "text" => "Capacidad flexible para colas de overflow, volumen estacional, cobertura extendida y necesidades crecientes."],
            ],
            "why" => "EmpireOneCX ayuda a programas enfocados en Paraguay a escalar con onboarding estructurado, manejo seguro de flujos, monitoreo de calidad y capacidad práctica.",
            "industries" => ["Retail y eCommerce", "Viajes y hotelería", "Servicios financieros", "Telecomunicaciones", "Servicios profesionales", "Logística"],
        ],
        "sudafrica" => [
            "name" => "Sudáfrica",
            "english_slug" => "south-africa",
            "image" => "/assets/images/south-africa-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Sudáfrica",
            "subtitle" => "Equipos de CX y BPO en inglés con alineación a servicios globales.",
            "intro" => "EmpireOneCX ayuda a marcas a escalar experiencia del cliente en inglés, back office, QA y operaciones asistidas por IA con capacidad alineada a Sudáfrica.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Sudáfrica para atención al cliente en inglés, QA, back office y cobertura global flexible.",
            "overview" => "Sudáfrica es una opción sólida para organizaciones que necesitan soporte en inglés, alineación global y cobertura flexible. EmpireOneCX apoya entrega enfocada en Sudáfrica con agentes capacitados, equipos back office, QA y flujos seguros.",
            "services" => [
                ["title" => "Soporte en inglés", "text" => "Servicio al cliente por voz, correo, chat y canales digitales para marcas con clientes globales de habla inglesa."],
                ["title" => "Control de calidad", "text" => "Monitoreo QA, coaching, reportes y soporte de conocimiento para mejorar consistencia entre equipos."],
                ["title" => "Operaciones back office", "text" => "Soporte administrativo y de procesos para datos, actualizaciones CRM, documentos y colas de tickets."],
            ],
            "why" => "Nuestro modelo en Sudáfrica ayuda a combinar servicio en inglés, cobertura global, flujos seguros y QA estructurado.",
            "industries" => ["Retail y eCommerce", "Servicios financieros", "Viajes y hotelería", "SaaS y tecnología", "Seguros", "Servicios profesionales"],
        ],
        "pakistan" => [
            "name" => "Pakistán",
            "english_slug" => "pakistan",
            "image" => "/assets/images/pakistan-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Pakistán",
            "subtitle" => "Equipos calificados de CX, soporte técnico, back office y operaciones asistidas por IA.",
            "intro" => "EmpireOneCX ayuda a empresas a escalar atención al cliente, asistencia técnica, operaciones administrativas y flujos asistidos por IA con equipos alineados a Pakistán.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Pakistán para soporte técnico, back office, operaciones asistidas por IA y dotación escalable.",
            "overview" => "Pakistán ofrece talento operativo calificado para atención al cliente, asistencia técnica, back office y soporte de procesos habilitado por IA. EmpireOneCX apoya programas alineados a Pakistán con agentes capacitados, documentación, QA y operaciones seguras.",
            "services" => [
                ["title" => "Soporte técnico", "text" => "Soporte por niveles para incidencias de clientes, colas help desk, diagnóstico y asistencia de producto o servicio."],
                ["title" => "Operaciones back office", "text" => "Soporte administrativo para ingreso de datos, actualizaciones CRM, procesamiento documental, reportes y trabajo recurrente."],
                ["title" => "Flujos asistidos por IA", "text" => "Soporte para enrutamiento, QA, base de conocimiento, reportes y automatización de flujos repetitivos."],
            ],
            "why" => "EmpireOneCX ayuda a equipos alineados a Pakistán a entregar soporte escalable con capacitación estructurada, procesos seguros, capacidad técnica y visibilidad de desempeño.",
            "industries" => ["SaaS y tecnología", "Retail y eCommerce", "Soporte de salud", "Servicios financieros", "Telecomunicaciones", "Servicios profesionales"],
        ],
        "filipinas" => [
            "name" => "Filipinas",
            "english_slug" => "philippines",
            "image" => "/assets/images/philippines-skyline.webp",
            "title" => "Soporte de outsourcing CX y BPO en Filipinas",
            "subtitle" => "Equipos consolidados de atención al cliente en inglés y BPO para marcas en crecimiento.",
            "intro" => "EmpireOneCX ayuda a empresas a escalar experiencia del cliente de alta calidad, soporte de voz y digital, back office y QA con capacidad alineada a Filipinas.",
            "metaDescription" => "EmpireOneCX ofrece soporte CX y BPO en Filipinas para atención al cliente en inglés, soporte de voz y digital, back office y monitoreo de calidad.",
            "overview" => "Filipinas es un destino consolidado para atención al cliente, servicio en inglés y entrega BPO. EmpireOneCX apoya programas alineados a Filipinas con equipos CX capacitados, especialistas back office, monitoreo QA y flujos seguros.",
            "services" => [
                ["title" => "Equipos de atención al cliente", "text" => "Equipos dedicados de voz, correo, chat y soporte omnicanal capacitados en su marca, productos, políticas y tono de servicio."],
                ["title" => "Soporte de voz y digital", "text" => "Soporte para llamadas entrantes, seguimiento saliente, chat en vivo, colas de correo y flujos help desk."],
                ["title" => "Monitoreo de calidad", "text" => "Scorecards de QA, coaching, reportes y mejora de procesos para una entrega consistente."],
            ],
            "why" => "EmpireOneCX ayuda a empresas a usar entrega alineada a Filipinas para escalar soporte en inglés con prácticas BPO maduras, flujos seguros y QA sólido.",
            "industries" => ["Retail y eCommerce", "SaaS y tecnología", "Soporte de salud", "Servicios financieros", "Viajes y hotelería", "Seguros"],
        ],
    ];

    return $locations[$slug] ?? null;
}
