<?php

function industry_page_data_es(string $slug): ?array
{
    $pages = [
        "bpo-comercio-minorista" => [
            "name" => "Retail",
            "english_slug" => "retail-bpo",
            "image" => "indus1.webp",
            "hero" => "Creado para retail. Listo para cada momento del cliente.",
            "audience" => "retailers, marcas omnicanal, marketplaces y empresas de productos de consumo",
            "challenge" => "Los equipos de retail deben gestionar demanda estacional, mayores expectativas de servicio, pedidos complejos y presión sobre los márgenes en todos los canales de atención.",
            "outcome" => "proteger la lealtad del cliente, mejorar la precisión de los pedidos y escalar el soporte sin aumentar los costos fijos",
            "services" => [
                "Atención omnicanal al cliente" => "Soporte por teléfono, chat, correo electrónico y redes sociales|Consultas sobre productos y disponibilidad|Resolución de reclamos y escalamiento",
                "Gestión de pedidos" => "Ingreso y validación de pedidos|Actualizaciones sobre el estado del pedido|Cancelaciones y modificaciones",
                "Devoluciones y reembolsos" => "Soporte para autorizaciones de devolución|Coordinación de reembolsos|Procesamiento de cambios y reemplazos",
                "Soporte para programas de fidelización" => "Registro de miembros|Consultas sobre puntos y recompensas|Campañas de retención y recuperación",
                "Operaciones de catálogo e inventario" => "Mantenimiento de datos de productos|Actualizaciones de inventario|Revisión de calidad de SKU y publicaciones",
                "Servicios back office para retail" => "Ingreso y conciliación de datos|Coordinación con proveedores|Reportes y control de calidad",
            ],
            "segments" => "Retailers omnicanal|Atención al cliente, gestión de pedidos y devoluciones;Marcas de consumo|Soporte de producto, fidelización y coordinación de garantías;Marketplaces|Soporte a vendedores, operaciones de catálogo y gestión de disputas;Retail especializado|Soporte de citas, consultas de producto y retención;Comercio por suscripción|Soporte de cuentas, renovaciones y recuperación de pagos",
        ],
        "bpo-automotriz" => [
            "name" => "Automotriz",
            "english_slug" => "automotive-bpo",
            "image" => "indus2.webp",
            "hero" => "BPO automotriz para cada etapa del recorrido del cliente.",
            "audience" => "fabricantes de vehículos, grupos de concesionarios, empresas de movilidad, proveedores de repuestos y redes de servicio",
            "challenge" => "Las organizaciones automotrices equilibran operaciones complejas de concesionarios, programación de servicios, flujos de garantía, clientes conectados y altas expectativas de respuesta.",
            "outcome" => "fortalecer la lealtad del propietario, acelerar los flujos de servicio y dar a los concesionarios capacidad operativa confiable",
            "services" => [
                "Atención al cliente y asistencia en carretera" => "Asistencia entrante para propietarios|Coordinación de casos de asistencia en carretera|Escalamiento y seguimiento",
                "Programación de servicios" => "Reserva de citas|Campañas de recall|Recordatorios de mantenimiento",
                "Soporte a concesionarios" => "Mesa de ayuda para concesionarios|Actualizaciones de CRM|Enrutamiento y seguimiento de leads",
                "Administración de garantías y reclamos" => "Recepción de reclamos|Validación de documentos|Comunicación de estado",
                "Gestión de ventas y leads" => "Calificación de leads|Programación de pruebas de manejo|Reactivación de clientes",
                "Back office automotriz" => "Ingreso de datos de vehículos|Soporte para pedidos de repuestos|Reportes y control de calidad",
            ],
            "segments" => "OEMs|Atención a propietarios, recalls y soporte de garantías;Grupos de concesionarios|Programación, gestión de leads y soporte CRM;Proveedores de movilidad|Soporte a usuarios y conductores, gestión de casos;Proveedores de repuestos|Soporte de pedidos, consultas de concesionarios y procesamiento de datos;Empresas de vehículos eléctricos|Soporte de carga, onboarding y servicios conectados",
        ],
        "bpo-viajes-hoteleria" => [
            "name" => "Viajes y hotelería",
            "english_slug" => "travel-hospitality-bpo",
            "image" => "indus3.webp",
            "hero" => "Soporte de experiencia del huésped desde la reserva hasta el regreso.",
            "audience" => "aerolíneas, hoteles, plataformas de viaje, operadores turísticos, alquileres vacacionales y marcas de movilidad",
            "challenge" => "La demanda de viajes cambia con rapidez, las interrupciones ocurren sin aviso y los huéspedes esperan ayuda inmediata y empática en cada zona horaria.",
            "outcome" => "ofrecer atención ágil al huésped, recuperar viajes interrumpidos y mantener la calidad del servicio las 24 horas",
            "services" => [
                "Soporte de reservas" => "Nuevas reservas|Cambios de reserva|Consultas de disponibilidad y tarifas",
                "Gestión de interrupciones" => "Soporte de cancelaciones|Asistencia para nuevas reservas|Flujos de notificación a huéspedes",
                "Servicios al huésped" => "Asistencia previa a la llegada|Soporte durante la estancia|Seguimiento posterior a la estancia",
                "Operaciones de programas de fidelización" => "Atención a miembros|Consultas sobre puntos|Soporte de niveles y beneficios",
                "Back office de viajes" => "Procesamiento de itinerarios|Verificación de documentos|Conciliación con proveedores",
                "Soporte digital para viajes" => "Soporte por chat y mensajería|Gestión de respuestas a reseñas|Atención social y escalamiento",
            ],
            "segments" => "Aerolíneas|Reservas, soporte ante interrupciones y fidelización;Hoteles y resorts|Atención al huésped, reservas y soporte posestancia;Agencias de viaje en línea|Soporte de reservas, reembolsos y coordinación con proveedores;Alquileres vacacionales|Soporte a huéspedes y anfitriones, resolución de casos;Operadores turísticos|Soporte de itinerarios, documentación y atención al viajero",
        ],
        "bpo-telecomunicaciones" => [
            "name" => "Telecomunicaciones",
            "english_slug" => "telecommunications-bpo",
            "image" => "indus4.webp",
            "hero" => "Soporte de telecomunicaciones diseñado para clientes siempre conectados.",
            "audience" => "operadores móviles, proveedores de internet, compañías de cable, proveedores de red y marcas de servicios conectados",
            "challenge" => "Los clientes de telecomunicaciones esperan activación rápida, facturación confiable, ayuda técnica inmediata y comunicación clara durante interrupciones o cambios de servicio.",
            "outcome" => "reducir el tiempo de resolución, mejorar el desempeño en el primer contacto y proteger la retención de suscriptores",
            "services" => [
                "Soporte técnico de Nivel 1 a 3" => "Diagnóstico de conectividad|Soporte de dispositivos y routers|Escalamiento de tickets",
                "Atención a suscriptores" => "Consultas de planes y cuentas|Cambios de servicio|Resolución de reclamos",
                "Soporte de facturación y pagos" => "Consultas de facturas|Asistencia de pagos|Procesamiento de ajustes",
                "Provisionamiento y activación" => "Activación de nuevos servicios|Soporte de portabilidad numérica|Validación de pedidos",
                "Retención y recuperación" => "Prevención de cancelaciones|Soporte de ofertas|Campañas de reactivación",
                "Soporte de operaciones de red" => "Comunicaciones de interrupciones|Monitoreo de tickets|Coordinación de servicio en campo",
            ],
            "segments" => "Operadores móviles|Atención a suscriptores, facturación y retención;Proveedores de internet|Soporte técnico, activación y atención ante interrupciones;Operadores de cable|Atención de cuentas, cambios de servicio y diagnóstico;Proveedores de red|Mesa de ayuda técnica y administración de casos;Proveedores IoT|Soporte de dispositivos, onboarding y monitoreo",
        ],
        "bpo-seguros" => [
            "name" => "Seguros",
            "english_slug" => "insurance-bpo",
            "image" => "indus5.webp",
            "hero" => "BPO para seguros creado para precisión, confianza y rapidez.",
            "audience" => "aseguradoras de propiedad y daños, aseguradoras de vida, planes de salud, corredores, MGAs e insurtechs",
            "challenge" => "Las operaciones de seguros dependen de registros precisos, comunicación ágil con asegurados, flujos disciplinados de reclamos y controles regulatorios estrictos.",
            "outcome" => "acortar ciclos de procesamiento, mejorar el servicio al asegurado y escalar la administración con mayor control de calidad",
            "services" => [
                "Atención a asegurados" => "Consultas de cobertura|Cambios de póliza|Asistencia de facturación y pagos",
                "Soporte administrativo de reclamos" => "Primer aviso de pérdida|Recolección de documentos|Actualizaciones de estado de reclamos",
                "Administración de pólizas" => "Procesamiento de nuevos negocios|Endosos y renovaciones|Mantenimiento de datos de pólizas",
                "Soporte de suscripción" => "Recepción de solicitudes|Verificación de datos|Preparación de expedientes de riesgo",
                "Soporte a agentes y corredores" => "Soporte de citas|Consultas de comisiones|Escalamiento de casos",
                "Back office de seguros" => "Indexación de documentos|Control de calidad|Reportes y conciliación",
            ],
            "segments" => "Propiedad y daños|Servicio de pólizas, recepción de reclamos y renovaciones;Vida y anualidades|Procesamiento de solicitudes y administración de pólizas;Seguros de salud|Servicios a miembros, inscripción y soporte de reclamos;Corredores y MGAs|Soporte a agentes y administración de cotizaciones;Insurtechs|Atención digital, operaciones y procesamiento de datos",
        ],
        "bpo-salud" => [
            "name" => "Salud",
            "english_slug" => "healthcare-bpo",
            "image" => "indus6.webp",
            "hero" => "BPO de salud diseñado para atención, cumplimiento y continuidad.",
            "audience" => "proveedores de salud, clínicas, redes médicas, pagadores, empresas de tecnología sanitaria y equipos de atención al paciente",
            "challenge" => "Los equipos de salud deben manejar consultas sensibles, programación, documentación, autorizaciones, facturación y datos protegidos con precisión y cumplimiento.",
            "outcome" => "mejorar el acceso del paciente, reducir cargas administrativas y apoyar flujos de trabajo seguros y consistentes",
            "services" => [
                "Soporte a pacientes" => "Consultas entrantes|Orientación de servicios|Escalamiento de casos sensibles",
                "Programación de citas" => "Reservas y reprogramaciones|Recordatorios|Coordinación de disponibilidad",
                "Soporte de autorizaciones" => "Recepción de solicitudes|Revisión de documentos|Seguimiento de estado",
                "Back office médico" => "Ingreso de datos|Indexación de documentos|Control de calidad",
                "Soporte de facturación" => "Consultas de pagos|Actualizaciones de cuentas|Coordinación de saldos",
                "Operaciones compatibles" => "Flujos con acceso controlado|Protocolos de privacidad|Reportes operativos",
            ],
            "segments" => "Clínicas y proveedores|Atención a pacientes, citas y documentación;Pagadores|Servicios a miembros, autorizaciones y soporte de reclamos;Healthtech|Soporte de plataforma, onboarding y datos;Redes médicas|Coordinación centralizada y reportes;Atención virtual|Soporte digital, triaje administrativo y seguimiento",
        ],
        "bpo-energia" => [
            "name" => "Energía",
            "english_slug" => "energy-bpo",
            "image" => "indus7.webp",
            "hero" => "BPO de energía para servicio confiable y operaciones más inteligentes.",
            "audience" => "proveedores eléctricos, empresas de energía renovable, operadores de petróleo y gas, comercializadoras de energía y contratistas de servicio",
            "challenge" => "Las organizaciones de energía gestionan cuentas complejas, actividad en campo, datos de facturación, documentación regulatoria y continuidad del servicio ante cambios de demanda.",
            "outcome" => "mejorar la comunicación con clientes, mantener datos operativos precisos y apoyar una prestación de servicio confiable",
            "services" => [
                "Atención al cliente de energía" => "Consultas de cuentas|Solicitudes de servicio|Gestión de reclamos y escalamiento",
                "Operaciones de facturación" => "Soporte de facturas|Procesamiento de pagos|Flujos de ajustes de facturación",
                "Servicios de datos de medición" => "Ingreso de lecturas|Validación y manejo de excepciones|Reportes de consumo",
                "Coordinación de servicio en campo" => "Programación de órdenes de trabajo|Soporte de despacho técnico|Seguimiento de finalización",
                "Soporte de interrupciones e incidentes" => "Recepción de reportes de interrupción|Comunicación de estado|Documentación de casos",
                "Back office de cumplimiento" => "Documentación regulatoria|Revisión de calidad de datos|Reportes operativos",
            ],
            "segments" => "Comercializadoras de energía|Atención al cliente, facturación y retención;Energía renovable|Inscripción, soporte de servicio y operaciones de datos;Petróleo y gas|Administración back office y reportes;Redes de servicio en campo|Programación, despacho y órdenes de trabajo;Tecnología energética|Soporte técnico y onboarding de clientes",
        ],
        "bpo-servicios-publicos" => [
            "name" => "Servicios públicos",
            "english_slug" => "utility-bpo",
            "image" => "indus8.webp",
            "hero" => "BPO para servicios públicos que mantiene conectados a clientes y operaciones.",
            "audience" => "proveedores de electricidad, gas, agua, residuos y servicios públicos municipales",
            "challenge" => "Los proveedores de servicios públicos deben entregar servicios esenciales mientras atienden altos volúmenes de facturación, órdenes de servicio, interrupciones y reportes estrictos.",
            "outcome" => "elevar la capacidad de respuesta, mejorar la precisión de cuentas y coordinar flujos esenciales a escala",
            "services" => [
                "Atención al cliente de servicios públicos" => "Consultas de cuentas|Solicitudes de alta y baja|Resolución de reclamos",
                "Soporte de facturación y cobranzas" => "Explicación de facturas|Arreglos de pago|Gestión de cobranzas",
                "Gestión de órdenes de servicio" => "Solicitudes de conexión|Flujos de desconexión|Seguimiento de estado de órdenes",
                "Comunicaciones de interrupciones" => "Recepción de reportes|Notificaciones a clientes|Actualizaciones de restauración",
                "Procesamiento de medición y consumo" => "Validación de lecturas|Procesamiento de excepciones|Ingreso de datos de consumo",
                "Back office de servicios públicos" => "Procesamiento documental|Reportes regulatorios|Control de calidad de datos",
            ],
            "segments" => "Servicios eléctricos|Facturación, atención ante interrupciones y órdenes;Servicios de gas|Soporte de cuentas y coordinación en campo;Proveedores de agua|Atención al cliente y procesamiento de medición;Servicios municipales|Soporte a residentes, pagos y registros;Servicios de residuos|Programación, atención de cuentas y soporte de rutas",
        ],
        "bpo-tecnologia-saas" => [
            "name" => "Tecnología y SaaS",
            "english_slug" => "technology-bpo",
            "image" => "indus9.webp",
            "hero" => "BPO tecnológico creado para apoyar adopción y escala.",
            "audience" => "empresas SaaS, proveedores de software, marcas de hardware, plataformas cloud, fintechs y negocios tecnológicos emergentes",
            "challenge" => "Las empresas tecnológicas necesitan incorporar usuarios con rapidez, resolver problemas técnicos, mantener datos de producto y escalar operaciones sin frenar la innovación.",
            "outcome" => "acelerar la adopción del cliente, proteger la retención y ampliar la capacidad operativa junto con el crecimiento del producto",
            "services" => [
                "Soporte técnico" => "Diagnóstico de Nivel 1 a 3|Gestión de tickets|Documentación de errores y escalamiento",
                "Customer success para SaaS" => "Onboarding de usuarios|Campañas de adopción|Soporte de renovaciones",
                "Soporte de producto" => "Consultas de funcionalidades|Configuración de cuentas|Orientación de base de conocimiento",
                "Operaciones de confianza y seguridad" => "Revisión de contenido|Gestión de casos de usuarios|Escalamiento de políticas",
                "Operaciones de datos e IA" => "Anotación de datos|Revisión de calidad|Preparación de conjuntos de datos",
                "Back office tecnológico" => "Administración CRM|Procesamiento de pedidos|Reportes y QA",
            ],
            "segments" => "Plataformas SaaS|Onboarding, soporte técnico y retención;Tecnología de consumo|Atención de producto, garantía y diagnóstico;Servicios cloud|Soporte de usuarios y administración de cuentas;Empresas de IA|Anotación, moderación y calidad de datos;Fintechs|Operaciones de clientes y soporte de verificación",
        ],
        "bpo-gobierno-sector-publico" => [
            "name" => "Gobierno y sector público",
            "english_slug" => "government-bpo",
            "image" => "indus10.webp",
            "hero" => "Soporte para el sector público creado para acceso, precisión y responsabilidad.",
            "audience" => "agencias gubernamentales, municipios, autoridades públicas, entidades educativas y contratistas del gobierno",
            "challenge" => "Las organizaciones públicas deben mejorar el acceso ciudadano, procesar mayores volúmenes de casos, mantener registros precisos y ofrecer servicios transparentes dentro de políticas definidas.",
            "outcome" => "ampliar la capacidad de atención ciudadana, reducir atrasos administrativos y fortalecer la visibilidad del proceso",
            "services" => [
                "Centro de atención ciudadana" => "Consultas de programas|Orientación de solicitudes|Soporte de estado de casos",
                "Procesamiento de casos" => "Recepción de solicitudes|Revisión de documentos de elegibilidad|Actualizaciones de datos de casos",
                "Gestión de registros" => "Indexación documental|Solicitudes de registros|Soporte de archivo",
                "Soporte de programas públicos" => "Asistencia de inscripción|Programación de citas|Notificaciones salientes",
                "Validación de datos" => "Ingreso de datos|Revisión de duplicados|Control de calidad",
                "Reportes y cumplimiento" => "Reportes operativos|Preparación de archivos de auditoría|Monitoreo de SLA",
            ],
            "segments" => "Municipios|Servicio a residentes, permisos y programación;Programas de beneficios públicos|Inscripción, soporte de casos y documentación;Autoridades de transporte|Soporte a usuarios y gestión de casos;Agencias educativas|Soporte a solicitantes y procesamiento de registros;Contratistas gubernamentales|Operaciones de programas, reportes y QA",
        ],
        "outsourcing-procesos-legales" => [
            "name" => "Legal",
            "english_slug" => "legal-process-outsourcing",
            "image" => "indus11.webp",
            "hero" => "Outsourcing de procesos legales creado para precisión y confidencialidad.",
            "audience" => "firmas legales, departamentos jurídicos corporativos, proveedores de servicios legales, aseguradoras y equipos de cumplimiento",
            "challenge" => "Los equipos legales enfrentan mayores volúmenes documentales, presión de plazos, tareas rutinarias costosas y requisitos estrictos de precisión y confidencialidad.",
            "outcome" => "reducir la carga administrativa, organizar información legal y dar más tiempo a los abogados para trabajo sustantivo",
            "services" => [
                "Soporte de revisión documental" => "Clasificación de documentos|Apoyo en revisión de relevancia|Control de calidad",
                "Administración de contratos" => "Abstracción contractual|Ingreso de metadatos|Seguimiento de obligaciones",
                "Soporte de investigación legal" => "Investigación de casos y normas|Verificación de citas|Resúmenes de investigación",
                "Operaciones de e-discovery" => "Organización de datos|Codificación documental|Soporte de flujos de revisión",
                "Gestión de expedientes" => "Apertura de asuntos|Organización de archivos|Actualización de plazos y expedientes",
                "Back office legal" => "Soporte de facturación|Recepción de clientes|Registros y reportes",
            ],
            "segments" => "Firmas legales|Revisión documental, investigación y administración de casos;Equipos legales corporativos|Contratos, registros de cumplimiento e intake;Operaciones legales de seguros|Expedientes de reclamos y procesamiento documental;Tecnología legal|Soporte de plataforma y operaciones de datos;Equipos de cumplimiento|Monitoreo, registros y reportes",
        ],
        "bpo-servicios-financieros" => [
            "name" => "Servicios financieros",
            "english_slug" => "financial-services-bpo",
            "image" => "indus12.webp",
            "hero" => "BPO financiero creado para control y confianza del cliente.",
            "audience" => "bancos, prestamistas, fintechs, empresas de pagos, gestores patrimoniales y proveedores de servicios financieros",
            "challenge" => "Las organizaciones financieras deben ofrecer servicio rápido mientras mantienen transacciones precisas, controles disciplinados, manejo seguro de datos y procesos auditables.",
            "outcome" => "mejorar la precisión del procesamiento, fortalecer el soporte al cliente y escalar operaciones financieras controladas",
            "services" => [
                "Atención al cliente financiero" => "Consultas de cuentas|Soporte de transacciones|Gestión de reclamos",
                "Soporte de operaciones de préstamos" => "Recepción de solicitudes|Verificación documental|Administración de servicing",
                "Back office de pagos" => "Manejo de excepciones de pago|Soporte de conciliación|Administración de contracargos",
                "Soporte de operaciones KYC" => "Recolección de documentos de clientes|Validación de datos|Preparación de casos",
                "Cuentas por pagar y por cobrar" => "Procesamiento de facturas|Aplicación de pagos|Seguimiento de cartera vencida",
                "Reportes y conciliación" => "Conciliación de cuentas|Revisión de calidad de datos|Reportes de gestión",
            ],
            "segments" => "Bancos y cooperativas de crédito|Atención al cliente y administración de cuentas;Prestamistas|Procesamiento de solicitudes y soporte de servicing;Fintechs|Soporte digital y operaciones de verificación;Proveedores de pagos|Disputas, conciliación y soporte a comercios;Gestores patrimoniales|Administración de clientes, registros y reportes",
        ],
        "bpo-comercio-electronico" => [
            "name" => "eCommerce",
            "english_slug" => "ecommerce-bpo",
            "image" => "indus13.webp",
            "hero" => "BPO para eCommerce que convierte cada pedido en lealtad.",
            "audience" => "retailers en línea, marcas directas al consumidor, marketplaces, negocios por suscripción y empresas de social commerce",
            "challenge" => "Las marcas de eCommerce deben atender pedidos rápidos, consultas de entrega, devoluciones, operaciones de marketplace y conversaciones con clientes en múltiples canales.",
            "outcome" => "mejorar el soporte de conversión, reducir fricciones en pedidos y retener clientes después de cada compra",
            "services" => [
                "Atención al cliente de eCommerce" => "Consultas de producto antes de la compra|Asistencia de pedidos|Soporte poscompra",
                "Procesamiento de pedidos" => "Validación de pedidos|Actualizaciones de estado|Soporte de cancelaciones y modificaciones",
                "Gestión de devoluciones y reembolsos" => "Autorización de devoluciones|Coordinación de reembolsos|Soporte de cambios",
                "Operaciones de marketplace" => "Soporte a vendedores|Mantenimiento de publicaciones|Administración de disputas",
                "Gestión de catálogo" => "Ingreso de datos de producto|Enriquecimiento de contenido|Revisión de calidad de SKU",
                "Soporte de suscripciones" => "Cambios de cuenta|Asistencia de renovación|Recuperación de pagos",
            ],
            "segments" => "Marcas DTC|Atención al cliente, soporte de pedidos y retención;Retailers en línea|Pedidos, devoluciones y operaciones de catálogo;Marketplaces|Soporte a compradores y vendedores, disputas;Marcas por suscripción|Atención de cuentas, renovaciones y recuperación de pagos;Social commerce|Soporte por mensajería y administración de pedidos",
        ],
        "bpo-bienes-raices" => [
            "name" => "Bienes raíces",
            "english_slug" => "real-estate-bpo",
            "image" => "indus14.webp",
            "hero" => "BPO inmobiliario para impulsar leads, listados y atención a residentes.",
            "audience" => "corredurías, administradores de propiedades, desarrolladores, plataformas inmobiliarias, firmas hipotecarias y operadores de instalaciones",
            "challenge" => "Las organizaciones inmobiliarias gestionan leads sensibles al tiempo, datos de propiedades, solicitudes de residentes, documentos de transacción y coordinación con proveedores en portafolios distribuidos.",
            "outcome" => "responder más rápido a prospectos, organizar operaciones de propiedades y mejorar el servicio a residentes y clientes",
            "services" => [
                "Calificación de leads" => "Respuesta a leads entrantes|Calificación de prospectos|Programación de visitas",
                "Soporte de administración de propiedades" => "Consultas de residentes|Recepción de solicitudes de mantenimiento|Coordinación de renovaciones",
                "Administración de listados" => "Ingreso de datos de listados|Actualización de fotos y contenido|Revisiones de calidad MLS",
                "Coordinación de transacciones" => "Recolección de documentos|Seguimiento de hitos|Seguimiento con partes interesadas",
                "Soporte a inquilinos y residentes" => "Asistencia de mudanza|Consultas de cuentas|Escalamiento de incidencias",
                "Back office inmobiliario" => "Coordinación con proveedores|Mantenimiento de datos|Reportes de portafolio",
            ],
            "segments" => "Corredurías|Respuesta a leads, soporte de listados y transacciones;Administradores de propiedades|Atención a residentes y coordinación de mantenimiento;Desarrolladores|Soporte a compradores y programación de citas;Plataformas inmobiliarias|Soporte a usuarios y operaciones de listados;Operadores de instalaciones|Mesa de servicio y coordinación con proveedores",
        ],
        "bpo-videojuegos" => [
            "name" => "Videojuegos",
            "english_slug" => "gaming-bpo",
            "image" => "indus15.webp",
            "hero" => "Soporte para videojuegos creado para jugadores, comunidades y operaciones en vivo.",
            "audience" => "estudios de videojuegos, publishers, plataformas, organizaciones de esports y empresas de entretenimiento interactivo",
            "challenge" => "Las comunidades de videojuegos esperan soporte rápido y experto mientras los estudios gestionan cuentas, moderación, eventos en vivo, pagos y seguridad del jugador a escala global.",
            "outcome" => "proteger la experiencia del jugador, fortalecer comunidades y apoyar operaciones en vivo las 24 horas",
            "services" => [
                "Soporte a jugadores" => "Ayuda con cuentas y acceso|Consultas de juego|Resolución de tickets",
                "Soporte técnico de videojuegos" => "Diagnóstico de instalación|Soporte de conectividad|Documentación de errores",
                "Moderación de comunidades" => "Moderación de chat|Soporte de foros|Gestión de escalamiento",
                "Confianza y seguridad" => "Revisión de reportes de jugadores|Apoyo en cumplimiento de políticas|Escalamiento de casos de fraude",
                "Soporte de pagos y cuentas" => "Consultas de compras|Administración de reembolsos|Soporte de suscripciones",
                "Soporte de operaciones en vivo" => "Soporte de eventos|Comunicaciones a jugadores|Actualización de base de conocimiento",
            ],
            "segments" => "Estudios de videojuegos|Soporte a jugadores, casos técnicos y QA;Publishers|Soporte global y operaciones de comunidad;Plataformas de gaming|Atención de cuentas, pagos, confianza y seguridad;Organizaciones de esports|Soporte a participantes y operaciones de eventos;Juegos móviles|Soporte de alto volumen, moderación y retención",
        ],
        "bpo-servicios-hogar" => [
            "name" => "Servicios para el hogar",
            "english_slug" => "home-services-bpo",
            "image" => "indus16.webp",
            "hero" => "BPO para servicios del hogar que ayuda a reservar más trabajos y atender mejor a cada cliente.",
            "audience" => "empresas de HVAC, plomería, electricidad, limpieza, jardinería, control de plagas y servicios múltiples para el hogar",
            "challenge" => "Las empresas de servicios para el hogar pierden ingresos cuando no contestan llamadas, la agenda es ineficiente, los técnicos no tienen detalles completos o los clientes no reciben actualizaciones oportunas.",
            "outcome" => "capturar más demanda, mejorar la utilización de técnicos y entregar comunicación confiable al cliente",
            "services" => [
                "Atención de llamadas entrantes" => "Gestión de consultas de servicio|Triaje de llamadas de emergencia|Captura de leads",
                "Programación de citas" => "Reservas y reprogramaciones|Coordinación de ventanas de servicio|Recordatorios",
                "Soporte de despacho" => "Apoyo en asignación de técnicos|Actualizaciones de ruta y estado|Notificaciones a clientes",
                "Seguimiento de cotizaciones" => "Seguimiento de presupuestos|Nutrición de leads|Recuperación de trabajos no reservados",
                "Atención al cliente" => "Consultas de estado de trabajo|Resolución de reclamos|Seguimiento posterior al servicio",
                "Back office de servicios del hogar" => "Ingreso de órdenes de trabajo|Administración de facturas|Mantenimiento de datos CRM",
            ],
            "segments" => "Empresas HVAC|Atención de llamadas, programación y despacho;Plomería y electricidad|Triaje de emergencias, reservas y seguimiento;Servicios de limpieza|Programación recurrente y atención de cuentas;Control de plagas|Soporte de citas y renovación;Franquicias multiservicio|Atención centralizada al cliente y operaciones",
        ],
        "bpo-garantia-hogar" => [
            "name" => "Garantía del hogar",
            "english_slug" => "home-warranty-bpo",
            "image" => "indus17.webp",
            "hero" => "BPO para garantía del hogar creado para reclamos más rápidos y mejor atención al propietario.",
            "audience" => "empresas de garantía del hogar, administradores de contratos de servicio, planes de protección de propiedades y redes de reparación",
            "challenge" => "Los proveedores de garantía del hogar coordinan necesidades urgentes, verificación de cobertura, redes de contratistas, aprobaciones, reclamos y seguimiento de servicio con alto volumen de casos.",
            "outcome" => "acelerar la gestión de reclamos, mejorar la comunicación con propietarios y coordinar redes de servicio con eficiencia",
            "services" => [
                "Atención a propietarios" => "Consultas de cobertura|Soporte de estado de reclamos|Resolución de reclamos",
                "Recepción y triaje de reclamos" => "Registro de nuevos reclamos|Clasificación de incidencias|Escalamiento de emergencias",
                "Verificación de cobertura" => "Revisión de planes y derechos|Apoyo en revisión de exclusiones|Validación de documentos",
                "Coordinación de contratistas" => "Asignación de proveedores de servicio|Coordinación de citas|Seguimiento de estado",
                "Soporte de autorizaciones" => "Recolección de estimaciones|Administración de flujos de aprobación|Comunicación de decisiones",
                "Back office de garantías" => "Documentación de reclamos|Apoyo en revisión de facturas|Reportes y control de calidad",
            ],
            "segments" => "Proveedores de garantía del hogar|Reclamos, atención al cliente y coordinación de contratistas;Administradores de contratos de servicio|Derechos, aprobaciones y registros;Administradores de propiedades|Reclamos de residentes y coordinación de reparaciones;Planes de electrodomésticos|Reclamos de producto y programación de servicio;Redes de reparación|Despacho, actualizaciones de estado y documentación",
        ],
        "bpo-transporte-logistica" => [
            "name" => "Transporte y logística",
            "english_slug" => "transportation-logistics-bpo",
            "image" => "indus18.webp",
            "hero" => "BPO logístico creado para visibilidad, velocidad y entregas confiables.",
            "audience" => "transportistas, freight forwarders, operadores 3PL, redes de entrega, brokers, almacenes y empresas tecnológicas de transporte",
            "challenge" => "Las operaciones de transporte dependen de comunicación en tiempo real, documentos precisos, visibilidad de envíos, manejo de excepciones y coordinación entre clientes, conductores y socios.",
            "outcome" => "mejorar la visibilidad de envíos, resolver excepciones con rapidez y mantener en movimiento la carga y la información",
            "services" => [
                "Soporte de seguimiento de envíos" => "Consultas de estado|Actualizaciones proactivas de envíos|Soporte de comprobantes de entrega",
                "Procesamiento de pedidos y cargas" => "Ingreso de pedidos|Administración de load tender|Validación de datos",
                "Coordinación de despacho" => "Comunicación con conductores|Programación de recogidas y entregas|Actualizaciones de ruta",
                "Documentación de carga" => "Procesamiento de bill of lading|Indexación documental|Apoyo en preparación de expedientes aduaneros",
                "Gestión de excepciones" => "Recepción de casos de retraso o daño|Coordinación de escalamiento|Comunicación con clientes",
                "Back office logístico" => "Soporte de auditoría de facturas|Mantenimiento de datos de transportistas|Reportes operativos",
            ],
            "segments" => "3PLs|Soporte de envíos, ingreso de pedidos y atención al cliente;Freight forwarders|Documentación, seguimiento y manejo de excepciones;Entrega de última milla|Soporte a conductores, despacho y actualizaciones a clientes;Transportistas y brokers|Administración de cargas y comunicación de estado;Almacenes|Programación de citas y procesamiento de datos",
        ],
    ];

    if (!isset($pages[$slug])) {
        return null;
    }

    $page = $pages[$slug];
    $page["slug"] = $slug;
    $page["primary_keyword"] = "servicios BPO para " . strtolower($page["name"]);
    $page["meta_title"] = "Servicios BPO para " . $page["name"] . " | EmpireOneCX";
    $page["meta_description"] = "EmpireOneCX ofrece servicios BPO especializados para " . strtolower($page["name"]) . ", incluyendo atención al cliente, back office, procesamiento de datos y operaciones escalables.";
    $page["keywords"] = implode(", ", [
        "BPO para " . strtolower($page["name"]),
        "servicios BPO para " . strtolower($page["name"]),
        "outsourcing para " . strtolower($page["name"]),
        "outsourcing de atención al cliente",
        "servicios back office",
        "business process outsourcing",
    ]);

    return $page;
}
